export default function PortfolioFooter() {
  return (
    <footer className="border-t border-slate-200 bg-white mt-12">
      <div className="w-full px-6 pt-4 pb-1 text-xs text-slate-400 font-light leading-relaxed">
        This tool and all example data it contains are created solely for portfolio and educational demonstration purposes. The example design changes, failure modes, severity ratings, and recommended actions are illustrative estimates generated by a large language model. They are not derived from, representative of, or associated with any proprietary review, internal process, confidential specification, or employer. Any resemblance to actual product parameters or internal analyses is coincidental. This tool is not intended for use in product design, safety validation, hardware acceptance testing, or any commercial application. All outputs should be reviewed and validated by qualified engineers before use in any real engineering context.
      </div>
      <div className="w-full px-6 py-4 flex items-center justify-end gap-4 flex-wrap text-xs text-slate-500">
        <div>
          Built by{' '}
          <img src="/claude-logo.svg" alt="Claude" className="inline-block w-4 h-4 mx-0.5 align-middle" />
          <span className="text-slate-500"> and </span>
          <img src="/avatar_pixel_v2.png" alt="Seoho" className="inline-block w-4 h-4 mx-0.5 align-middle rounded-sm" />
        </div>
      </div>
    </footer>
  )
}
